services:
  - type: web
    name: daveenci-authentication
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CLIENTS
        sync: false
      - key: ISSUER_URL
        value: https://authentication.daveenci.ai
      - key: COOKIE_DOMAIN
        value: .daveenci.ai
      - key: CORS_ORIGIN
        value: https://*.daveenci.ai
    customDomains:
      - authentication.daveenci.ai
    healthCheckPath: /health 